### ISSUE TITLE
Send me the git - cheat sheet

### ISSUE THREAD

**Issue by scottdhansen** [danz50of/PEERDEV#8]
@danz50of, I can't find the git cheat sheet you sent over.

**Comment by scottdhansen** [comment]
@danz50of Was this it?  https://services.github.com/kit/downloads/github-git-cheat-sheet.pdf

**Comment by danz50of** [comment]
Thank you,

Dan Zabinski
Peerless-AV
Direct: 630-375-6304

**Comment by danz50of** [comment]
This looks like it is updated from the one I had.

Thank you,

Dan Zabinski
Peerless-AV
Direct: 630-375-6304

**Comment by danz50of** [comment]
Sent.  Closing issue.
